# Generated by Django 2.0.4 on 2018-04-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmTitle', models.CharField(max_length=300)),
                ('duration', models.IntegerField(default=1)),
                ('director', models.CharField(max_length=150)),
                ('releaseDate', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
